---
title: "PaqueteActividadGrupal"
output: html_document
---

## ACTIVIDAD GRUPAL 

Equipo: Tamara, Joshua, Joel

Evaluamos 4 paquetes diferentes. Todos los paquetes analizados parecen funcionar en todos los sistemas operativos. La mayoría de los paquetes son muy recientes y con descargas insuficientes para determinar todos los posibles errores o complicaciones no previstas que puedan surgir a la hora de usarlos.  

El paquete elegido fue: **GWENA**
[GWENA](https://github.com/Kumquatum/GWENA)

*---------- The development of high-throughput sequencing led to increased use of co-expression analysis to go beyong single feature focus. We propose GWENA (Gene Whole co-Expression Network Analysis) , a tool designed to perform gene co-expression network analysis and explore the results in a single pipeline. It includes functional enrichment of modules of co-expressed genes, phenotypcal association, topological analysis and comparison of networks configuration between conditions.*



Desde el Overview y documentación, con figuras y recursos gráficos se ve la dedicación que le da a que se entienda la teoría del paquete y la parte técnica de su funcionamiento. Es bastante descriptiva con toda la explicación. Los Issues del GitHub fueron contestados por la autora a los 3 días, lo cual parece muy buena atención y disposición de ayudar. 
Tiene más descargar que los demás paquetes y más interacción. Además, es el más actualizado. 

